FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN apt-get update -y && \
    apt-get install -y awscli && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python3", "app.py"]